### ISSUE TITLE
Classic Era / SoD - Hunter range not working correctly

### ISSUE THREAD

**Issue by ensey** [WeakAuras/LibRangeCheck-3.0#16]
Game version: Classic ERA
Class: Hunter
Spec: MM (increased range)

I am using an addon, ElvUI, which rangecheck depends on this library, after range was semi-locked by Blizzard, when they modernized the classic UI.

ElvUI has a feature that fades unitframes, when out of range.
After Blizzard change the rangecheck and the addon since depended on this library, the unitframe fades at 25-28 yards, instead of the maximum 41 yards, which is the talented max range of hunters.

There is a github issue, that also explains this here:
https://github.com/tukui-org/ElvUI/issues/1137

**Comment by mrbuds** [comment]
You need to provide a minimal code using the lib showing the problem, with steps to reproduce.

"Elvui frames doesn't work as intended" is not a valid bug report.

**Comment by ensey** [comment]
> You need to provide a minimal code using the lib showing the problem, with steps to reproduce.
> 
> "Elvui frames doesn't work as intended" is not a valid bug report.

ElvUI imports LibRangeCheck and uses it in range.lua and core.lua

range.lua: 
`local E, L, V, P, G = unpack(ElvUI)
local UF = E:GetModule('UnitFrames')
local RangeCheck = E.Libs.RangeCheck

local UnitCanAttack = UnitCanAttack
local UnitInRange = UnitInRange
local UnitIsConnected = UnitIsConnected
local UnitIsPlayer = UnitIsPlayer
local UnitIsUnit = UnitIsUnit
local UnitInPhase = UnitInPhase
local UnitPhaseReason = UnitPhaseReason

local function getMaxRange(unit)
	local minRange, maxRange = RangeCheck:GetRange(unit, true, true)
	return (not minRange) or maxRange
end

local function friendlyIsInRange(realUnit)
	local unit = E:GetGroupUnit(realUnit) or realUnit

	if UnitIsPlayer(unit) and (E.Retail and UnitPhaseReason(unit) or not E.Retail and not UnitInPhase(unit)) then
		return false -- is not in same phase
	end

	local inRange, checkedRange = UnitInRange(unit)
	if checkedRange and not inRange then
		return false -- blizz checked and said the unit is out of range
	end

	return getMaxRange(unit)
end

function UF:UpdateRange(unit)
	if not self.Fader then return end
	local alpha

	unit = unit or self.unit

	if self.forceInRange or unit == 'player' then
		alpha = self.Fader.MaxAlpha
	elseif self.forceNotInRange then
		alpha = self.Fader.MinAlpha
	elseif unit then
		if UnitCanAttack('player', unit) or UnitIsUnit(unit, 'pet') then
			alpha = (getMaxRange(unit) and self.Fader.MaxAlpha) or self.Fader.MinAlpha
		else
			alpha = (UnitIsConnected(unit) and friendlyIsInRange(unit) and self.Fader.MaxAlpha) or self.Fader.MinAlpha
		end
	else
		alpha = self.Fader.MaxAlpha
	end

	self.Fader.RangeAlpha = alpha
end
`

The relevanat code that depends on the range check in core.lua is here - it is also the basis for the function that sets fade based on range:
`-- [Fader] Range check options for Units
		do
			local outsideAlpha
			if E.db.unitframe.OORAlpha ~= nil then
				outsideAlpha = E.db.unitframe.OORAlpha
				E.db.unitframe.OORAlpha = nil
			end

			for _, unit in ipairs({'target','targettarget','targettargettarget','focus','focustarget','pet','pettarget','boss','arena','party','raid1','raid2','raid3','raidpet','tank','assist'}) do
				if E.db.unitframe.units[unit].rangeCheck ~= nil then
					local enabled = E.db.unitframe.units[unit].rangeCheck
					E.db.unitframe.units[unit].fader.enable = enabled
					E.db.unitframe.units[unit].fader.range = enabled

					if outsideAlpha then
						E.db.unitframe.units[unit].fader.minAlpha = outsideAlpha
					end

					E.db.unitframe.units[unit].rangeCheck = nil
				end
			end
		end`

I am not native in lua, so forgive me my shortcomings.
I hope this is sufficient to describe the issue

**Comment by jjholleman** [comment]
@ensey They need steps to reproduce. In this case it would be useful to share your ElvUI profile and hunter talents.

**Comment by E-Tsx** [comment]
the issue for hunter (and warrior) is that all the spells with minrange dont get added to the harmRC or harmNoItemsRC tables, (test auto shot, and throw and see, they are not in the tables, only a few items), the unitframes fade at 28 yards, which is the interact:4 fallback. If you remove that one from the list the frames fade at 8 yards interact:3, if you instead add a spell like hunter mark to the list the frames will only fade out at 100 yards as its a spell that has no minrange.

**Comment by ensey** [comment]
@mrbuds Can we please have this issue reopened?

Steps to reproduce
Install ElvUI
Go to Unitframes, Choose target, choose fader and enable it.
Add range as fade condition.

Fading happens according to @E-Tsx description, and it fades as out of range at 28 yards, instead of at correct max range. 

![Skærmbillede 2024-02-26 kl  08 09 24](https://github.com/WeakAuras/LibRangeCheck-3.0/assets/4716832/3575ba38-b64e-4a77-8eb0-6021ac0887a7)

**Comment by mrbuds** [comment]
> Can we please have this issue reopened?

> Steps to reproduce Install ElvUI ....

If issue require elvui to be installed it's an elvui problem

**Comment by ensey** [comment]
> > Can we please have this issue reopened?
> 
> > Steps to reproduce Install ElvUI ....
> 
> If issue require elvui installed to be reproduced then it's an elvui problem, we need a minimal example only using the lib
> 
> Edit: From your screenshot nothing show how the lib is called, what it returns and what is the expected result This lib doesn't have a generalist "is this unit out of range" function, it gives a minimal & maximal possible distance between you and a unit, what elvui consider to be out of range is their business

Have you seen my previous reply with code-examples?

Also, did you see the reply from @E-Tsx, that describe how spells with minrange isn't added to the table harmRC?

**Comment by InfusOnWoW** [comment]
The code example is a apparently a straight copy from the elvui sources, it's useless.

The description by E-Tsx hints at a problem, but that lacks proper details to figure out what they meant.

The elvui developers need to debug this to figure out what goes wrong, or provide a small self-contained example that shows the problem. We won't be debugging elvui for them, they need to handle that. You need to adress questions to them, not us.

**Comment by ensey** [comment]
> The code example is a apparently a straight copy from the elvui sources, it's useless.
> 
> The description by E-Tsx hints at a problem, but that lacks proper details to figure out what they meant.
> 
> The elvui developers need to debug this to figure out what goes wrong, or provide a small self-contained example that shows the problem. We won't be debugging elvui for them, they need to handle that. You need to adress questions to them, not us.

They are pointing at the lib having issues, at that the question should be here.

I have tried @E-Tsx suggestion of Hunter's Mark, and after saving the file and reloading UI, they unitframe stays unfaded until 100 yards, and then fades to transparent.

It is like the lib does not accept abilities with minrange at all, as a source for maxrange.

Unfortunately for this, hunters does not have any abilities without minrange and with the correct maxrange of attack abilties.
All ranged attack abilities have a deadzone min range.

**Comment by ensey** [comment]
@mrbuds @Stanzilla 
When will kodewdles changes be implemented?

**Comment by Stanzilla** [comment]
> @mrbuds @Stanzilla 
> 
> When will kodewdles changes be implemented?

When they make a pull request and it gets approved and merged
