### ISSUE TITLE
TWW pre patch: another lua error

### ISSUE THREAD

**Issue by BlartVersenwald** [WeakAuras/LibRangeCheck-3.0#29]
Just taking portal from Vindicator > Hope's Landing

1x .../Plater/libs/LibRangeCheck-3.0-20/LibRangeCheck-3.0.lua:638: attempt to perform arithmetic on local 'offset' (a nil value)
[string "@Plater/libs/LibRangeCheck-3.0-20/LibRangeCheck-3.0.lua"]:638: in function <.../Plater/libs/LibRangeCheck-3.0/LibRangeCheck-3.0.lua:636>
[string "@Plater/libs/LibRangeCheck-3.0-20/LibRangeCheck-3.0.lua"]:646: in function <.../Plater/libs/LibRangeCheck-3.0/LibRangeCheck-3.0.lua:642>
[string "@Plater/libs/LibRangeCheck-3.0-20/LibRangeCheck-3.0.lua"]:663: in function <.../Plater/libs/LibRangeCheck-3.0/LibRangeCheck-3.0.lua:661>
[string "@Plater/libs/LibRangeCheck-3.0-20/LibRangeCheck-3.0.lua"]:739: in function <.../Plater/libs/LibRangeCheck-3.0/LibRangeCheck-3.0.lua:716>
[string "@Plater/libs/LibRangeCheck-3.0-20/LibRangeCheck-3.0.lua"]:1033: in function `init'
[string "@Plater/libs/LibRangeCheck-3.0-20/LibRangeCheck-3.0.lua"]:1344: in function `initialOnUpdate'
[string "@Plater/libs/LibRangeCheck-3.0-20/LibRangeCheck-3.0.lua"]:1424: in function <.../Plater/libs/LibRangeCheck-3.0/LibRangeCheck-3.0.lua:1418>

Locals:
_ = nil
_ = nil
offset = nil
numSpells = nil
(*temporary) = 5
(*temporary) = "attempt to perform arithmetic on local 'offset' (a nil value)"

**Comment by mrbuds** [comment]
Looks like lib:init() (called from initialOnUpdate) is called before C_SpellBook.GetSpellBookSkillLineInfo can return anything

**Comment by InfusOnWoW** [comment]
I couldn't reproduce that issue, though I think the fix is pretty obvious anyway.
