### ISSUE TITLE
Using Lightning Bolt to check range for Enh Shaman causes incorrect return value when Tempest procs

### ISSUE THREAD

**Issue by WoW-Dai** [WeakAuras/LibRangeCheck-3.0#35]
For Enhancement Shamans, when Tempest procs, LibRangeCheck rangeChecker returns an incorrect value for a short period of time for 40 yards (returns nil instead of true). 

This was noticed due to plater incorrectly fading out nameplates that were in melee when tempest procs,

Maybe change the spell to check ranges to to something like Chain Lighting to workaround this issue? For Enhance I used flameshock instead of lightning bolt and it seems to work but I think Ele might get increased range on flame shock.

**Comment by InfusOnWoW** [comment]
I think that should have been fixed by https://github.com/WeakAuras/LibRangeCheck-3.0/commit/50a1a83fe1e434d50da9a7415ec8ba776b11e2b1

Can you check what exact version you are using?

**Comment by InfusOnWoW** [comment]
I'm waiting for more information from you.
