### ISSUE TITLE
Error when logging in certain classes

### ISSUE THREAD

**Issue by zaphon** [WeakAuras/LibRangeCheck-3.0#36]
I've been getting the following error when logging on random different characters the past few days. I checked to make sure that the latest version of LibRangeCheck is what is being used and it is.

The issue (from my testing) is that _G.GetSpellBookItemInfo is somehow being set and used (I have no idea how, I can't find another of my AddOns that's setting that), plus if that was the case it should fail on all characters. But it doesn't.

I just removed the check for _G.GetSpellBookItemInfo and left it as a function since the code that calls it will only work with this function anyway.

```
6029x ...dFrames/Libs/LibRangeCheck-3.0-26/LibRangeCheck-3.0.lua:664: attempt to index local 'spellInfo' (a number value)
[string "@EnhancedRaidFrames/Libs/LibRangeCheck-3.0-26/LibRangeCheck-3.0.lua"]:664: in function <...dFrames/Libs/LibRangeCheck-3.0/LibRangeCheck-3.0.lua:655>
[string "@EnhancedRaidFrames/Libs/LibRangeCheck-3.0-26/LibRangeCheck-3.0.lua"]:683: in function <...dFrames/Libs/LibRangeCheck-3.0/LibRangeCheck-3.0.lua:681>
[string "@EnhancedRaidFrames/Libs/LibRangeCheck-3.0-26/LibRangeCheck-3.0.lua"]:759: in function <...dFrames/Libs/LibRangeCheck-3.0/LibRangeCheck-3.0.lua:736>
[string "@EnhancedRaidFrames/Libs/LibRangeCheck-3.0-26/LibRangeCheck-3.0.lua"]:1056: in function `init'
[string "@EnhancedRaidFrames/Libs/LibRangeCheck-3.0-26/LibRangeCheck-3.0.lua"]:1364: in function `initialOnUpdate'
[string "@EnhancedRaidFrames/Libs/LibRangeCheck-3.0-26/LibRangeCheck-3.0.lua"]:1444: in function <...dFrames/Libs/LibRangeCheck-3.0/LibRangeCheck-3.0.lua:1438>

Locals:
spellName = "Shoot"
(for index) = 3
(for limit) = 132
(for step) = 1
i = 3
spell = "Shoot"
spellType = 3
spellID = 16809449
spellInfo = 32233
(*temporary) = <table> {
 Spell = 1
 PetAction = 3
 Flyout = 4
 FutureSpell = 2
 None = 0
}
(*temporary) = 3
(*temporary) = "attempt to index local 'spellInfo' (a number value)"
BOOKTYPE_SPELL = 0

```

**Comment by InfusOnWoW** [comment]
Is that on retail, classic era, season of discovery?

**Comment by zaphon** [comment]
Sorry Retail.

**Comment by InfusOnWoW** [comment]
On retail GetSpellBookItemInfo is not supposed to exist. Can you try disabling all other addons and check with 
/dump GetSpellBookItemInfo that it doesn't exist and then reenable addons until /dump GetSpellBookItemInfo does print something?

**Comment by zaphon** [comment]
Agreed it shouldn't, and I've been going through my addons trying to figure out who could be defining it (as I can call it, it exists, and it's returning the data that it's direct replacement C_SpellBook.GetSpellBookItemType returns which is why the check you are doing (validating the 3rd return value exists) is failing in my case.) I'll close this for now.
