### ISSUE TITLE
Spells from talents no longer working on era

### ISSUE THREAD

**Issue by Eegjrgngdbnreegbue** [WeakAuras/LibRangeCheck-3.0#40]
After a recent patch, the library no longer checks for range of spells learned from talents on era. For example, the library can not check for 24yd with a shadow reached mind flay.

**Comment by InfusOnWoW** [comment]
What is a "shadow reached" mind flay?

**Comment by Stanzilla** [comment]
> What is a "shadow reached" mind flay?

https://www.wowhead.com/classic/spell=17323/shadow-reach buffs the range

**Comment by Eegjrgngdbnreegbue** [comment]
> Oh that requires level 25, that's not something I can reasonable do.
> 
> Looking at the spell list "Mind Flay" is not in there, are you saying that adding a line: tinsert(HarmSpells.PRIEST, 15407) -- Mind Flay (20-24 yards) would allow the library to check more ranges?

I've had the line: tinsert(HarmSpells.PRIEST, 15407) -- Mind Flay
added in my local file since forever (or equivalent line in 2.0 of the library). It was working until a wow patch broke it during 1.0.16 of the library, and got quickly fixed in 1.0.17. Now it is broken again in 1.0.17 after another wow patch.
